
spring:
  application:
    name: gateway
  cloud:
    circuitbreaker:
      resilience4j: enabled
    gateway:
      discovery:
        locator:
          # 将服务进行转发 http://网关地址/服务名/uri
          enabled: true
          # eureka服务转发地址弄成小写的，http://网关地址/服务名/uri，服务名变成小写的
          lower-case-service-id: true
      filter:
        request-rate-limiter:
#          deny-empty-key: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/,http://localhost:9091/eureka/,http://localhost:9092/eureka/
server:
  port: 9080
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/rsa/publicKey"