
spring:
  application:
    name: gateway
  cloud:
    circuitbreaker:
      resilience4j: enabled
    gateway:
      discovery:
        locator:
          enabled: true
      filter:
        request-rate-limiter:
#          deny-empty-key: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/,http://localhost:9091/eureka/,http://localhost:9092/eureka/
server:
  port: 9080